### ISSUE TITLE
Better ways of handling virtual classes, default constructors, etc?

### ISSUE THREAD

**Issue by fuchstraumer** [eliasdaler/MetaStuff#14]
I'm really enjoying this library so far - it's made serialization of a lot of objects in my current project loads easier. However, I was curious if there's any way to handle inherited members and serializing those? I have several classes in this codebase that inherit from each other, and usually these base classes are registered with metastuff along with their derived class children.

However, the only way to set the value of an inherited member in a child class is by adding the member like so (wherein C_Satellite is the base, here):

```
template<>
inline auto registerMembers<C_Payload>() {
    return members(
        member("Name", &C_Satellite::dm_str_SatelliteName),
        member("Position", &C_Satellite::X),
        member("Velocity", &C_Satellite::V),
        member("Mass", &C_Satellite::dm_num_Mass),
        member("DragCrossSection", &C_Payload::mf_Get_DragCrossSection, &C_Payload::mf_Set_DragCrossSection),
        member("MomentOfInertia", &C_Payload::Inertia),
        member("EulerAngle", &C_Payload::EulerAngle),
        member("Type", &C_Satellite::GetSatelliteTypeStr, &C_Satellite::SetSatelliteTypeWithStr)
    );
}
```
This can be really quite the hassle, and things that aren't explicitly added brings me to my next point - default constructors. Is there any way a default constructor could be called, before serializing the values? That way, everything is safely initialized but can still be overwritten by the reflected/serialized input data. I've thought of adding some cheeky bool variable like `initialized`, and making the getter for that effectively useless and having the setter call a setup function - but this seems less than ideal and results in me writing some kind of "initialized" variable to JSON in many cases.

A lot of these are also partially design issues in my application (sorry!) but its a very old legacy codebase and I simply don't have the time I'd like to have to really dive into the architecture and classes and refactor out the virtual stuff where I can. Cheers!

**Comment by eliasdaler** [comment]
Glad you enjoy the library! I'm certainly glad to hear that it's being used by someone. :)

As for inheritance, check out [this demo](https://gist.github.com/eliasdaler/45bf3f583cd4a41019b9802c198e6f41). Does it do what you want? I didn't implement an easy way to do this with MetaStuff yet, because I don't know how to make it clear and convenient enough, but I'm thinkikg about it.

As for initialization. Just initialize your class instance and then pass it in [this function](https://github.com/eliasdaler/MetaStuff/blob/master/example/JsonCast.h#L51) (if you're using JSON example).

It will only overwrite the data which is present in JSON, and this can be used to "override" only selected fields of the class (e.g. have some "base" JSON which will serialize all the fields and "override" JSON which will only change fields which are present in it).

**Comment by fuchstraumer** [comment]
Figures that most of the stuff already existed, I just didn't see it (oops!).

that inheritance example will work splendidly, and the default constructor bit works well too - particularly abashed that I didn't notice that first! Thanks for the prompt reply and clarifying things, I appreciate it and hope to keep using your library :)

**Comment by eliasdaler** [comment]
I think I need to write it in the README, as it's wasn't there. :)

Glad it works for you, feel free to ask questions here or send me an e-mail. The library may also lack some needed features, so don't hesitate to ask for them, as currently it's pretty basic and may not have things you'll need.
